import test from 'node:test';import assert from 'node:assert/strict';import {notificationHidden,READY_CONTROL_TEXT,HUD_TEXT_BOUNDS,LONGEST_GROUND_REASON,notificationReservations,reservationFamily,reservationStatesForFamily,reservationPhase} from '../src/hud-notification-reservations';
test('source bounds use AA2 and the 30-second prediction horizon',()=>{assert.deepEqual(HUD_TEXT_BOUNDS,{aaPerTarget:2,gunReloadSeconds:6,bombReloadSeconds:20,predictionSeconds:30,loopSeconds:2,respawnSeconds:5,groundCount:272});assert.equal(LONGEST_GROUND_REASON,'全経路閉塞・後方待避を待機');});
test('inactive player families share warning/reload/payload space without removing their own status',()=>{for(const phase of ['waiting','spectating'] as const){const [r]=notificationReservations(phase);assert.equal(r.warning,'');assert.equal(r.reload,'');assert.equal(r.payload,'');assert.match(r.status,/5\.0秒.*経路待機 272体.*全経路閉塞・後方待避を待機/);assert.equal(r.bombAmmo,'残り0発');assert.equal(r.bombHint,'予測なし');assert.equal(r.loop,'すぐ使える');assert.equal(reservationFamily(phase),'inactive');}assert.equal(reservationStatesForFamily('waiting').length,2);});
test('payload only coexists with effective guide; longer terrain guide is reserved separately',()=>{const rows=notificationReservations('flying');assert.equal(rows.length,3);for(const r of rows){assert.match(r.warning,/対空.*2門.*低空注意.*空域境界/);assert.match(r.reload,/6\.0秒/);assert.match(r.status,/経路待機/);if(r.payload)assert.match(r.bombHint,/^有効圏 30\.0秒$/);if(r.bombHint.startsWith('地形着弾'))assert.equal(r.payload,'');}assert.equal(rows.find(r=>r.id==='flying-ineffective')!.bombHint,'地形着弾 30.0秒');});
test('active-player presence, not a stale text label, determines reservation family',()=>{assert.equal(reservationPhase(true,'waiting'),'flying');assert.equal(reservationPhase(false,'spectating'),'spectating');assert.equal(reservationPhase(false,'flying'),'waiting');});
test('a currently empty notification does not shrink a flying family reservation between frames',()=>{const rows=reservationStatesForFamily('flying');assert.ok(rows.some(r=>r.payload));assert.ok(rows.every(r=>r.reload&&r.warning&&r.status));assert.equal(reservationFamily('flying'),'flying');});

test('ready control words remain reserved while current cooldown labels are narrower',()=>{assert.deepEqual(READY_CONTROL_TEXT,{loop:'すぐ使える',bombAmmo:'残り2発',bombHint:'予測なし'});});

test('empty payload and status retain their actual grid item while warning/reload hide',()=>{for(const id of ['payload-status','control-status'])assert.equal(notificationHidden(id,''),false);for(const id of ['warning','reload-status']){assert.equal(notificationHidden(id,''),true);assert.equal(notificationHidden(id,'visible'),false);}});
