import test from 'node:test';import assert from 'node:assert/strict';import {REGISTRY,SCENARIOS,inspectDiagnostic,inspectBrowserEnvelope,ENVELOPES,PROFILES} from '../diagnostics/layout-reservation/contracts';
const box={x:0,y:0,width:44,height:44};
const complete=()=>({records:REGISTRY.map(id=>{const p=PROFILES.find(p=>id.startsWith(p.id+':'))!;return {id,gpuTargetSubmitted:1,pageErrors:[],consoleErrors:[],nativeState:{screen:'playing',tick:1,queue:{completedCount:1}},scenarios:SCENARIOS.map(name=>({name,nodeCount:8,viewport:{width:p.width,height:p.height},nodes:['warning','reload-status','payload-status','control-status','ally-announcements','loop-status','bomb-ammo','bomb-hint'].map(id=>({id,text:'fixture',hiddenByAncestor:false,fontSize:'12px',box,clientBox:box,fragments:[],textNodes:[],clipAncestors:[]})),controls:['pause','game-sound','fire','loop','throttle','bomb'].map(id=>({id,hidden:false,box})),sight:{x:100,y:100,radius:40,margin:8},conflicts:[]}))};})});
test('all8 profiles and all3 scenarios complete measurement only, never product acceptance',()=>{const r=inspectDiagnostic(complete());assert.equal(r.complete,true);assert.equal(r.productAcceptance,false);assert.equal(REGISTRY.length,8);});
test('missing profile/scenario/geometry and environment errors fail measurement closed',()=>{for(const mutate of [(d:ReturnType<typeof complete>)=>{d.records.pop();},(d:ReturnType<typeof complete>)=>{d.records[0].scenarios.pop();},(d:ReturnType<typeof complete>)=>{d.records[0].scenarios[0].nodes=[];},(d:ReturnType<typeof complete>)=>{d.records.push(d.records[0]);}]){const d=complete();mutate(d);assert.equal(inspectDiagnostic(d).complete,false);}assert.equal(inspectDiagnostic(null).complete,false);assert.equal(inspectDiagnostic({records:[{id:REGISTRY[0],error:'GPU unavailable'}]}).complete,false);});
test('source envelopes retain warning, reload, prediction and respawn information',()=>{assert.match(ENVELOPES.flying.warning,/対空.*低空注意.*空域境界/);assert.match(ENVELOPES.flying.reload,/6\.0秒/);assert.match(ENVELOPES.flying.payload,/命中保証ではありません/);assert.match(ENVELOPES.waiting.status,/復帰待ち.*5\.0秒.*経路待機/);});

test('diagnostic runner errors and retries are never hidden by complete geometry',()=>{
 const make=()=>({stats:{expected:1,unexpected:0,skipped:0,flaky:0},errors:[] as string[],suites:[{specs:[{title:'layout-reservation-diagnostic',tests:[{results:[{status:'passed',errors:[] as string[]}]}]}]}]});
 assert.deepEqual(inspectBrowserEnvelope(make()),[]);const a=make();a.errors.push('runner error');assert.ok(inspectBrowserEnvelope(a).length);const b=make();b.suites[0].specs[0].tests[0].results.push(b.suites[0].specs[0].tests[0].results[0]);assert.ok(inspectBrowserEnvelope(b).length);const c=make();c.suites[0].specs[0].tests[0].results[0].status='failed';assert.ok(inspectBrowserEnvelope(c).length);
});

test('completed native count must cover the actual target submission',()=>{const d=complete();d.records[0].gpuTargetSubmitted=2;assert.equal(inspectDiagnostic(d).complete,false);});
